export { SectionWrapper } from './SectionWrapper';
export { NameSection } from './NameSection';
export { PhotoSection } from './PhotoSection';
export { ProfileSection } from './ProfileSection';
export { ContactSection } from './ContactSection';
export { ExperienceSection } from './ExperienceSection';
export { EducationSection } from './EducationSection';
export { SkillsSection } from './SkillsSection';
export { LanguagesSection } from './LanguagesSection';
